name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  Qt_patch_version: 5.15.16
  
jobs:
  Build-Win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Download Qt
        shell: cmd
        working-directory: C:\
        run: |
          mkdir Qt
          mkdir MPVPlayer
          git clone https://github.com/faojdoai324234s/Qt-Win-V2.git Qt
          xcopy /y /v /s /e D:\a\MPV-GP\MPV-GP C:\MPVPlayer
          rmdir /s /q D:\a\MPV-GP\MPV-GP
          
      - name: Download and build libmpv
        shell: cmd
        working-directory: C:\MPVPlayer
        run: |
          mkdir include
          mkdir lib
          
      - name: Build library
        shell: cmd
        working-directory: C:\MPVPlayer
        run: |
          cmake -B build -D Qt5_DIR="C:\Qt\Qt-${{ env.Qt_patch_version }}/lib/cmake/Qt5"
          cmake --build build --config Debug
          rmdir /s /q build
          cmake -B build -D Qt5_DIR="C:\Qt\Qt-${{ env.Qt_patch_version }}/lib/cmake/Qt5"
          cmake --build build --config Release
