name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  platform: Win
  Qt_patch_version: 5.15.16
  
jobs:
  Build-Win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Download dependencies
        shell: cmd
        working-directory: C:\
        run: |
          mkdir Qt
          mkdir MPVPlayer
          git clone https://github.com/faojdoai324234s/Qt-Win-V2.git Qt
          xcopy /y /v /s /e D:\a\MPV-GP\MPV-GP C:\MPVPlayer
          rmdir /s /q D:\a\MPV-GP\MPV-GP
          dir C:\MPVPlayer
          
      - name: Build library
        shell: cmd
        run: |
          agit clone https://github.com/faojdoai324234s/Qt-${{ env.platform }}.git
          acmake -B build -D Qt5_DIR="Qt-${{ env.platform }}/Qt-${{ env.Qt_patch_version }}/lib/cmake/Qt5"
          acmake --build build --config Debug
          armdir /s /q build
          acmake -B build -D Qt5_DIR="Qt-${{ env.platform }}/Qt-${{ env.Qt_patch_version }}/lib/cmake/Qt5"
          acmake --build build --config Release
